[workspace]
members = [
    #"examples/dapps-staking",
#    "examples/rmrk",
#    "examples/rooster-contract",
    # "examples/assets",
    "examples/signing",
    #a "contracts/**"
]
exclude = [
    "crates/dapps-staking",
    "crates/rmrk"
]
